spring:
  application:
    name: service-discovery

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8671/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8761