spring:
  application:
    name: technician-service
  datasource:
    url: jdbc:h2:file:~/technicians;AUTO_SERVER=true
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop


  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always

axon:
  serializer:
    events: jackson

